// Motor Control Circuit
// Generated by Circuit AI Design Assistant

#define MOTOR_PIN 9
#define SPEED_PIN A0

void setup() {
  pinMode(MOTOR_PIN, OUTPUT);
  Serial.begin(9600);
}

void loop() {
  int speedValue = analogRead(SPEED_PIN);
  int motorSpeed = map(speedValue, 0, 1023, 0, 255);
  analogWrite(MOTOR_PIN, motorSpeed);
  
  Serial.print("Motor Speed: ");
  Serial.println(motorSpeed);
  delay(100);
}