// Motor Control Circuit
// Generated by Circuit AI

#define MOTOR_PIN 9
#define SPEED_PIN A0

void setup() {
  pinMode(MOTOR_PIN, OUTPUT);
  Serial.begin(9600);
}

void loop() {
  int speed = analogRead(SPEED_PIN);
  int motorSpeed = map(speed, 0, 1023, 0, 255);
  analogWrite(MOTOR_PIN, motorSpeed);
  delay(100);
}